services:
  mongo:
    image: mongo:7
    container_name: cybernest-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - cybernest_mongo_data:/data/db

volumes:
  cybernest_mongo_data:
